
# set default task and default training config based on task
defaults:
  - task: Cartpole
  - agent: ${task}PPO
  - _self_

  # - hydra/job_logging: disabled
  # - override hydra/job_logging: colorlog
  # - override hydra/hydra_logging: colorlog

# set the directory where the output files get saved
hydra:
  searchpath:
    - pkg://isaacgymenvs/cfg
  output_subdir: null
  run:
    dir: .
  job_logging:
    formatters:
      simple:
        format: "[%(levelname)s: %(module)s:%(lineno)d %(asctime)s] %(message)s"

# Task name - used to pick the class to load
task_name: ${task.name}
experiment: ''
# if set to positive integer, overrides the default number of environments
num_envs: ''

## Logging
# logdir: 'debug'
logdir: 'workdir/${task.name}'
wandb:
  mode: offline  # online | offline | disabled
  project: project_name
  group: group_name
  resume: allow
  # save_code: True

## PhysX arguments
physics_engine: 'physx'  # physx | flex
pipeline: 'gpu'  # gpu | cpu
num_threads: 4  # Number of worker threads per scene used by PhysX - for CPU PhysX only.
solver_type: 1  # 0: pgs, 1: tgs
num_subscenes: 4  # Splits the simulation into N physics scenes and runs each one in a separate thread

## Device config
device_id: 0  # 'cuda:?', -1 for 'cpu'
# device for running physics simulation
sim_device: ???
# device to run RL
rl_device: ???
# which Vulkan graphics device ID to use for rendering
graphics_device_id: 0
# disables rendering
headless: True
# whether to call env.render(mode='rgb_array')
env_render: False
# whether to use multi-gpu training with `huggingface.Accelerate`
multi_gpu: False

## Run Arguments
run: 'train'  # train | eval | train_eval
ckpt: ''  # ckpt file to load
ckpt_keys: ''  # set to '' to load all ckpt keys

seed: 42  # set to -1 to choose random seed
torch_deterministic: False  # force the usage of deterministic algorithms in PyTorch
